/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JButton;

/**
 *
 * @author Andric
 */
public class vistaBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form vistaBienvenida
     */
    public vistaBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        liqvehibtn = new javax.swing.JButton();
        liqLotebtn = new javax.swing.JButton();
        liqvivbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        liqvehibtn.setText("Liquidar Vehiculo");

        liqLotebtn.setText("Liquidar Lote");

        liqvivbtn.setText("Liquidar Vivienda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(liqvehibtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(liqLotebtn)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(liqvivbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liqLotebtn)
                    .addComponent(liqvehibtn))
                .addGap(31, 31, 31)
                .addComponent(liqvivbtn)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaBienvenida().setVisible(true);
            }
        });

    }

    public vistaBienvenida(JButton liqLotebtn, JButton liqvehibtn, JButton liqvivbtn) {
        this.liqLotebtn = liqLotebtn;
        this.liqvehibtn = liqvehibtn;
        this.liqvivbtn = liqvivbtn;
    }

    public JButton getLiqLotebtn() {
        return liqLotebtn;
    }

    public void setLiqLotebtn(JButton liqLotebtn) {
        this.liqLotebtn = liqLotebtn;
    }

    public JButton getLiqvehibtn() {
        return liqvehibtn;
    }

    public void setLiqvehibtn(JButton liqvehibtn) {
        this.liqvehibtn = liqvehibtn;
    }

    public JButton getLiqvivbtn() {
        return liqvivbtn;
    }

    public void setLiqvivbtn(JButton liqvivbtn) {
        this.liqvivbtn = liqvivbtn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton liqLotebtn;
    private javax.swing.JButton liqvehibtn;
    private javax.swing.JButton liqvivbtn;
    // End of variables declaration//GEN-END:variables
}
